services:
  - name: healthycoffee-backend
    type: web
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: cd model && gunicorn --bind 0.0.0.0:$PORT app:app --workers 1 --threads 2 --timeout 120
